export default Users = [
    {
        id: 1,
        email: 'user1@email.com',
        username: 'user1',
        password: 'password',
        userToken: 'token123',
        firstName: 'Igjae',
        lastName: 'So',
        company: 'IT Company',
    },
    {
        id: 2,
        email: 'user2@email.com',
        username: 'user2',
        password: 'pass123',
        userToken: 'token12345',
        firstName: 'Iggy',
        lastName: 'So',
        company: 'IT Center',
    },
    {
        id: 3,
        email: 'user3@email.com',
        username: 'user3',
        password: 'testpass',
        userToken: 'testtoken',
        firstName: 'John',
        lastName: 'Parker',
        company: 'IT Solution',
    },
]